#include<iostream.h>
#include<conio.h>
void main()
{
    const int rno=12;
    char name[40]={"Rahul Patel"};
    char grade='A';
     char mobile_no[10]={"9825413612"};
    int age=16;
    char address[30]={"Saraspur"};
    char city[40]={"Ahmedabad"};
    char state[20]={"Gujarat"};
    int zipcode=354510;
    clrscr();
	  cout<<"===========================================\n";
	  cout<<"Student Rno: "<<rno<<endl;
	  cout<<"Student Name:"<<name<<endl;
	  cout<<"Student Grade:"<<grade<<endl;
	  cout<<"Student Mobile Number:"<<mobile_no<<endl;
	  cout<<"Student Age:"<<age<<endl;
	  cout<<"Student Address:"<<address<<endl;
	  cout<<"Student City:"<<city<<endl;
	  cout<<"Student State:"<<state<<endl;
	  cout<<"Student Zipcode:"<<zipcode<<endl;
    getch();

}